name: Build Docker Image
on:
  push:
    branches:
      - master

jobs:
  generate-build-number-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Build Number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Print Build Number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Build Docker Image
        run: ${PWD}/build-docker
