name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  generate-build-number-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Give build permissions
        run: chmod -R 777 .\build-docker
      - name: Build Docker Image
        run: ${PWD}/build-docker
